version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8-browser
steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn ng build --prod
      - run: yarn ng test --single-run

